# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: test

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
              $tenantPath = './azureadexporter.json'
                  $tenantId = '220781bd-82b6-4316-bf67-c170b415ed23'
                  Write-Host 'git checkout main...'
                  git config --global core.longpaths true
                  git checkout main
                  
                  Write-Host 'Clean git folder...'
                  
                  Write-Host 'Installing modules...'
                  Install-Module Microsoft.Graph.Authentication -Scope CurrentUser -Force
                  Install-Module AzureADExporter -Scope CurrentUser -Force
                  
                  Write-Host 'Connecting to AzureAD...'
                  Connect-AzureADExporter  -TenantId $tenantId
                  
                  Write-Host 'Starting backup...'
                  Export-AzureAD $tenantPath -All
